### ISSUE TITLE
Umbraco version switcher sends you to frontpage of documentation

### ISSUE THREAD

**Issue by MichaelNielsenDK** [vendrhub/vendr-documentation#91]
So if your search for something, and you select something, it will default show the v9 documentation, but if you switch to v8, you'll just end up on the frontpage of the documentation. If you search for the same thing again, it will default back to v9. 

Don't know if it's possible for it to remember your version selection, and when switching, to stay on the page you were looking at.

**Comment by mattbrailsford** [comment]
Hmmm, at the very least the search is meant to be version specific (although maybe because I split the docs into two umbraco version I didn't take that into account). I'll look into that and see if I can get that working better.

Will have to see what can be done with the switcher to stay on the same doc page too 👍

**Comment by mattbrailsford** [comment]
OK, both of these should be fixed now.

It'll take at least 24 hours for our search provider to reindex our content, but it should now differentiate between Umbraco versions and the search should just give you results meant for these selected version you are on.

Additionally, the Umbraco Version dropdown should now attempt to send you to the same docs page for the given version if one exists and if it doesn't, it will then send you to the home page.
